/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CCodeCaller */

#ifndef _Included_CCodeCaller
#define _Included_CCodeCaller
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CCodeCaller
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CCodeCaller_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
