/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIPrimitiveTest */

#ifndef _Included_JNIPrimitiveTest
#define _Included_JNIPrimitiveTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIPrimitiveTest
 * Method:    avg
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_JNIPrimitiveTest_avg
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
