/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CPPCodeCaller */

#ifndef _Included_CPPCodeCaller
#define _Included_CPPCodeCaller
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CPPCodeCaller
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CPPCodeCaller_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
